### ISSUE TITLE
typo in `thermal_expansion_coefficient.m`

### ISSUE THREAD

**Issue by chrishavlin** [vbr-calc/vbr#129]
The docstring has:

```
    % Output
    % -------
    % Rho : scalar or array
    %     density in same units as input density
```

but the output is actually the coefficient of thermal expansion. Need to fix that. This is in `vbr/vbrCore/functions/density/thermal_expansion_coefficient.m`

**Comment by phershbe** [comment]
I am a self-taught developer who stopped for a while, feel free to let me know if there are any problems with the pull request.
