### ISSUE TITLE
A small problem in Poroelasticity module

### ISSUE THREAD

**Issue by wuzm-iggcas** [vbr-calc/vbr#23]
Report for version: vbr-0.99.3
Dear authors,
I accidentally found some inconsistency when comparing my own calculation with the output of 'anh_poro'.
After going thorugh the related source code, I think the formulas taken from eqns A5-6, Takei 2002 (at Line 107 & 149, in el_ModUnrlx_MELT_f.m) have not been correctly quoted in the script, and should be corrected as follows:
n_k = a_vec(1) .* Psi + a_vec(2) .* (1-Psi) + a_vec(3) .* Psi .* (1-Psi).^1.5 ;
n_mu = b_vec(1) .* Psi + b_vec(2) .* (1-Psi) + b_vec(3) .* Psi .* (1-Psi).^2;
Best,
Zimu

**Comment by chrishavlin** [comment]
Thanks for the report! I'll check it out.
